site_name: CipherPass PRO
site_description: Documentación oficial y referencia de la API para CipherPass PRO.
site_author: Eduardo Mallo

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - scheme: slate
      primary: blue
      accent: indigo

plugins:
  - search

nav:
  - Inicio: index.md
  - Arquitectura de Seguridad: security_architecture.md